"""Packager — turn a Blueprint into a self-contained delivery directory / ZIP.

Pipeline (each step emits a PackagerProgress event):
    1. validate    — schema is already valid; cross-check asset references
    2. layout      — create output dir tree
    3. copy_backend — copy backend/ minus tests/debug junk
    4. copy_frontend — copy frontend/dist if it exists, else mark as "build needed"
    5. copy_assets  — skills / mcp-servers / extra_paths
    6. write_env    — generate .env.example
    7. write_compose — generate docker-compose.yml from prod template
    8. write_lock   — freeze blueprint into blueprint.lock.yaml
    9. write_readme — generate README_DEPLOY.md
   10. zip          — optional — bundle into <name>-<version>.zip

The packager is intentionally pure file-system: no network, no docker calls.
docker image bundling is left for a future ``--format docker`` mode.
"""

from __future__ import annotations

import json
import shutil
import zipfile
from collections.abc import Callable, Iterable
from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

import yaml

from .assets import REPO_ROOT, scan_assets
from .schema import (
    Blueprint,
    PlatformModeEnum,
    UIModeEnum,
)

ProgressStatus = Literal["start", "ok", "skip", "warn", "error"]


@dataclass
class PackagerProgress:
    step: str
    status: ProgressStatus
    detail: str = ""


@dataclass
class PackagerResult:
    output_dir: Path
    zip_path: Path | None = None
    files_written: int = 0
    bytes_written: int = 0
    warnings: list[str] = field(default_factory=list)


# ── File-copy filters ───────────────────────────────────────────────────────
# Pattern matching is intentionally simple: substring match on the relative path.
# This is faster than fnmatch and good enough for the directory layouts here.

_BACKEND_EXCLUDE_DIRS = {
    "__pycache__",
    "__pycache__old",
    ".pytest_cache",
    ".mypy_cache",
    "htmlcov",
    "tests",
    "benchmarks",
    "data",
    "start_data",
    "exports",
    "logs",
    "storage",
    "hivemind_rag.egg-info",
}

_BACKEND_EXCLUDE_FILE_PREFIXES = (
    "test_",
    "debug_",
    "eval_",
    "check_",
    "dump_",
    "list_routes",
    "mcp_test",
    "mcp_swarm_test",
    "dummy_mcp_server",
    "temp.",
    "out.",
    "trace.",
)

_BACKEND_EXCLUDE_SUFFIXES = (".pyc", ".log", ".db", ".db-journal")


def _backend_filter(rel: Path) -> bool:
    """Return True to include the file, False to skip."""
    parts = rel.parts
    if any(part in _BACKEND_EXCLUDE_DIRS for part in parts):
        return False
    name = rel.name
    if name.startswith(_BACKEND_EXCLUDE_FILE_PREFIXES):
        return False
    if name.endswith(_BACKEND_EXCLUDE_SUFFIXES):
        return False
    return True


def _copy_tree(src: Path, dst: Path, predicate: Callable[[Path], bool]) -> tuple[int, int]:
    """Copy ``src`` → ``dst`` honouring ``predicate(rel_path)``. Returns (files, bytes)."""
    files = 0
    total_bytes = 0
    for entry in src.rglob("*"):
        if entry.is_dir():
            continue
        rel = entry.relative_to(src)
        if not predicate(rel):
            continue
        target = dst / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(entry, target)
        files += 1
        total_bytes += entry.stat().st_size
    return files, total_bytes


# ── Compose template ────────────────────────────────────────────────────────
# Kept inline (no Jinja) to avoid adding a runtime dep just for one file.

_COMPOSE_TEMPLATE = """# Auto-generated by hivemind export — DO NOT edit by hand.
# Re-run the export to update.
version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: {name}-backend:{version}
    env_file: .env
    environment:
      PLATFORM_MODE: "{platform_mode}"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    image: nginx:1.27-alpine
    volumes:
      - ./frontend_dist:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: hivemind
      POSTGRES_PASSWORD: ${{POSTGRES_PASSWORD:?set in .env}}
      POSTGRES_DB: hivemind
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
"""


_README_TEMPLATE = """# {name} — {customer}

Auto-generated delivery package · version {version} · platform mode `{platform_mode}` · UI mode `{ui_mode}`

{description}

## Quick start (intranet)

```bash
# 1. Configure secrets
cp .env.example .env
# edit .env — set POSTGRES_PASSWORD and your LLM credentials

# 2. (Offline only) load pre-baked images
# docker load -i images/backend.tar
# docker load -i images/postgres.tar

# 3. Bring it up
docker compose up -d

# 4. Verify
curl http://localhost:8000/api/v1/health/
# Open http://localhost/ in a browser
```

## What's inside

- `backend/` — FastAPI app (modules pruned to `{platform_mode}` mode)
- `frontend_dist/` — Pre-built static UI ({ui_mode_note})
- `skills/` — {skill_count} skill(s) bundled
- `mcp-servers/` — {mcp_count} MCP server(s) bundled
- `blueprint.lock.yaml` — frozen spec used to generate this package

## Re-generate

This package was produced from a blueprint. To rebuild after editing the spec:

```bash
python scripts/export_blueprint.py path/to/blueprint.yaml --output dist/{name}
```
"""


# ── Packager ────────────────────────────────────────────────────────────────


class Packager:
    """Render a Blueprint into a delivery directory.

    Parameters
    ----------
    blueprint:
        Validated Blueprint instance.
    output_dir:
        Destination directory. Will be created. If it exists and is non-empty,
        ``overwrite=True`` is required.
    repo_root:
        Source repo root. Defaults to the repo this script lives in.
    """

    def __init__(
        self,
        blueprint: Blueprint,
        output_dir: Path,
        repo_root: Path | None = None,
        overwrite: bool = False,
    ):
        self.bp = blueprint
        self.output_dir = Path(output_dir)
        self.repo_root = repo_root or REPO_ROOT
        self.overwrite = overwrite
        self.result = PackagerResult(output_dir=self.output_dir)

    # Subclass hook — base impl is no-op; CLI/API plug a callback in.
    def on_progress(self, event: PackagerProgress) -> None:  # pragma: no cover - default
        pass

    def _emit(self, step: str, status: ProgressStatus, detail: str = "") -> None:
        self.on_progress(PackagerProgress(step=step, status=status, detail=detail))

    # ── Steps ───────────────────────────────────────────────────────────

    def _step_validate(self) -> None:
        self._emit("validate", "start")
        catalog = scan_assets(self.repo_root)
        known_skills = {a.id for a in catalog.skills}
        known_mcp = {a.id for a in catalog.mcp_servers}
        for agent in self.bp.agents:
            for s in agent.skills:
                if s not in known_skills:
                    self.result.warnings.append(
                        f"agent {agent.id!r} references unknown skill {s!r}"
                    )
                    self._emit("validate", "warn", f"unknown skill: {s}")
            for m in agent.mcp_servers:
                if m not in known_mcp:
                    self.result.warnings.append(
                        f"agent {agent.id!r} references unknown mcp server {m!r}"
                    )
                    self._emit("validate", "warn", f"unknown mcp_server: {m}")
        self._emit("validate", "ok")

    def _step_layout(self) -> None:
        self._emit("layout", "start")
        if self.output_dir.exists() and any(self.output_dir.iterdir()):
            if not self.overwrite:
                raise FileExistsError(
                    f"output dir is not empty: {self.output_dir} (pass overwrite=True)"
                )
            shutil.rmtree(self.output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self._emit("layout", "ok", str(self.output_dir))

    def _step_copy_backend(self) -> None:
        self._emit("copy_backend", "start")
        src = self.repo_root / "backend"
        if not src.exists():
            self._emit("copy_backend", "error", f"missing: {src}")
            raise FileNotFoundError(src)
        dst = self.output_dir / "backend"
        files, total = _copy_tree(src, dst, _backend_filter)
        self.result.files_written += files
        self.result.bytes_written += total
        self._emit("copy_backend", "ok", f"{files} files, {total / 1024:.1f} KB")

    def _step_copy_frontend(self) -> None:
        self._emit("copy_frontend", "start")
        if self.bp.ui_mode == UIModeEnum.WIDGET:
            self._emit("copy_frontend", "skip", "widget mode — bundle externally")
            return
        dist = self.repo_root / "frontend" / "dist"
        if not dist.exists():
            self.result.warnings.append(
                "frontend/dist not found — run `npm run build` before exporting "
                "if you need a pre-built UI in the package."
            )
            self._emit("copy_frontend", "warn", "frontend/dist missing — skipped")
            return
        target = self.output_dir / "frontend_dist"
        files, total = _copy_tree(dist, target, lambda _: True)
        self.result.files_written += files
        self.result.bytes_written += total
        self._emit("copy_frontend", "ok", f"{files} files, {total / 1024:.1f} KB")

    def _copy_filtered_dir(self, src: Path, dst: Path) -> tuple[int, int]:
        return _copy_tree(
            src,
            dst,
            lambda rel: not any(
                p.startswith((".", "_")) or p == "__pycache__" for p in rel.parts
            ),
        )

    def _step_copy_assets(self) -> None:
        self._emit("copy_assets", "start")
        wanted_skills: set[str] = set()
        wanted_mcp: set[str] = set()
        for agent in self.bp.agents:
            wanted_skills.update(agent.skills)
            wanted_mcp.update(agent.mcp_servers)

        for sid in sorted(wanted_skills):
            src = self.repo_root / "skills" / sid
            if not src.exists():
                self._emit("copy_assets", "warn", f"skill not found: {sid}")
                continue
            files, total = self._copy_filtered_dir(src, self.output_dir / "skills" / sid)
            self.result.files_written += files
            self.result.bytes_written += total

        for mid in sorted(wanted_mcp):
            src = self.repo_root / "mcp-servers" / mid
            if not src.exists():
                self._emit("copy_assets", "warn", f"mcp server not found: {mid}")
                continue
            files, total = self._copy_filtered_dir(
                src, self.output_dir / "mcp-servers" / mid
            )
            self.result.files_written += files
            self.result.bytes_written += total

        for extra in self.bp.extra_paths:
            src = self.repo_root / extra
            if not src.exists():
                self._emit("copy_assets", "warn", f"extra path not found: {extra}")
                continue
            target = self.output_dir / extra
            if src.is_file():
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(src, target)
                self.result.files_written += 1
                self.result.bytes_written += src.stat().st_size
            else:
                files, total = self._copy_filtered_dir(src, target)
                self.result.files_written += files
                self.result.bytes_written += total

        self._emit(
            "copy_assets",
            "ok",
            f"skills={len(wanted_skills)} mcp={len(wanted_mcp)} extras={len(self.bp.extra_paths)}",
        )

    def _step_write_env(self) -> None:
        self._emit("write_env", "start")
        env_path = self.output_dir / ".env.example"
        lines: list[str] = [
            f"# Auto-generated for {self.bp.name} v{self.bp.version} ({self.bp.customer})",
            "# DO NOT commit a real .env to source control.",
            "",
            f"PLATFORM_MODE={self.bp.platform_mode.value}",
        ]
        # LLM
        lines.append("")
        lines.append(f"# LLM ({self.bp.llm.provider.value})")
        lines.append(f"LLM_MODEL={self.bp.llm.model}")
        if self.bp.llm.base_url:
            if self.bp.llm.provider == self.bp.llm.provider.OPENAI:
                lines.append(f"OPENAI_BASE_URL={self.bp.llm.base_url}")
            else:
                lines.append(f"LLM_BASE_URL={self.bp.llm.base_url}")
        lines.append("OPENAI_API_KEY=changeme")
        # Postgres placeholder
        lines.extend(
            [
                "",
                "# Postgres",
                "POSTGRES_PASSWORD=changeme",
            ]
        )
        # User overrides
        overrides = self.bp.env_overrides.model_dump(exclude_none=True)
        if overrides:
            lines.append("")
            lines.append("# Overrides from blueprint.env_overrides")
            for k, v in overrides.items():
                if hasattr(v, "value"):
                    v = v.value  # Enum
                lines.append(f"{k}={v}")
        env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        self.result.files_written += 1
        self.result.bytes_written += env_path.stat().st_size
        self._emit("write_env", "ok", str(env_path.relative_to(self.output_dir)))

    def _step_write_compose(self) -> None:
        self._emit("write_compose", "start")
        compose = _COMPOSE_TEMPLATE.format(
            name=self.bp.name,
            version=self.bp.version,
            platform_mode=self.bp.platform_mode.value,
        )
        path = self.output_dir / "docker-compose.yml"
        path.write_text(compose, encoding="utf-8")
        self.result.files_written += 1
        self.result.bytes_written += path.stat().st_size
        self._emit("write_compose", "ok")

    def _step_write_lock(self) -> None:
        self._emit("write_lock", "start")
        lock = self.bp.model_dump(mode="json")
        path = self.output_dir / "blueprint.lock.yaml"
        path.write_text(yaml.safe_dump(lock, sort_keys=False, allow_unicode=True), encoding="utf-8")
        # Also write JSON for machine consumption.
        json_path = self.output_dir / "blueprint.lock.json"
        json_path.write_text(json.dumps(lock, ensure_ascii=False, indent=2), encoding="utf-8")
        self.result.files_written += 2
        self.result.bytes_written += path.stat().st_size + json_path.stat().st_size
        self._emit("write_lock", "ok")

    def _step_write_readme(self) -> None:
        self._emit("write_readme", "start")
        readme = _README_TEMPLATE.format(
            name=self.bp.name,
            customer=self.bp.customer,
            version=self.bp.version,
            description=self.bp.description or "_(no description)_",
            platform_mode=self.bp.platform_mode.value,
            ui_mode=self.bp.ui_mode.value,
            ui_mode_note=(
                "single-agent layout"
                if self.bp.ui_mode == UIModeEnum.SINGLE_AGENT
                else self.bp.ui_mode.value
            ),
            skill_count=sum(len(a.skills) for a in self.bp.agents),
            mcp_count=sum(len(a.mcp_servers) for a in self.bp.agents),
        )
        path = self.output_dir / "README_DEPLOY.md"
        path.write_text(readme, encoding="utf-8")
        self.result.files_written += 1
        self.result.bytes_written += path.stat().st_size
        self._emit("write_readme", "ok")

    def _step_zip(self, zip_target: Path) -> None:
        self._emit("zip", "start", str(zip_target))
        zip_target.parent.mkdir(parents=True, exist_ok=True)
        # Use ZIP_DEFLATED — universally supported and fast enough for ~MBs.
        with zipfile.ZipFile(zip_target, "w", zipfile.ZIP_DEFLATED) as zf:
            for entry in self.output_dir.rglob("*"):
                if entry.is_dir():
                    continue
                arcname = entry.relative_to(self.output_dir.parent)
                zf.write(entry, arcname=str(arcname))
        self.result.zip_path = zip_target
        self._emit("zip", "ok", f"{zip_target.stat().st_size / 1024:.1f} KB")

    # ── Public API ──────────────────────────────────────────────────────

    def run(self, make_zip: bool = False) -> PackagerResult:
        """Execute the full pipeline. Returns the populated PackagerResult."""
        self._step_validate()
        self._step_layout()
        self._step_copy_backend()
        self._step_copy_frontend()
        self._step_copy_assets()
        self._step_write_env()
        self._step_write_compose()
        self._step_write_lock()
        self._step_write_readme()
        if make_zip:
            zip_path = self.output_dir.parent / f"{self.bp.name}-{self.bp.version}.zip"
            self._step_zip(zip_path)
        self._emit("done", "ok", f"{self.result.files_written} files written")
        return self.result


# ── Convenience iterator (used by API streaming) ────────────────────────────


def run_with_progress(
    blueprint: Blueprint,
    output_dir: Path,
    *,
    make_zip: bool = False,
    overwrite: bool = False,
) -> Iterable[PackagerProgress]:
    """Generator wrapper — yields each progress event as it happens.

    Used by the SSE endpoint. Internally this just buffers the callback into a
    list since the underlying Packager pipeline is synchronous; for very large
    repos, refactor to push events through a queue.
    """
    events: list[PackagerProgress] = []
    pkg = Packager(blueprint, output_dir, overwrite=overwrite)
    pkg.on_progress = events.append  # type: ignore[method-assign]
    try:
        pkg.run(make_zip=make_zip)
    finally:
        for ev in events:
            yield ev
