"""create_missing_tables

Revision ID: 1f452e2c036e
Revises: fa6c0440d897
Create Date: 2026-04-14 08:20:30.657252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1f452e2c036e'
down_revision: Union[str, None] = 'fa6c0440d897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table('gov_prompt_definitions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recommended_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False), # Use String to avoid Enum creation issues
    sa.Column('change_log', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('meta_info', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gov_prompt_definitions_created_at'), 'gov_prompt_definitions', ['created_at'], unique=False)
    op.create_index(op.f('ix_gov_prompt_definitions_is_current'), 'gov_prompt_definitions', ['is_current'], unique=False)
    op.create_index(op.f('ix_gov_prompt_definitions_slug'), 'gov_prompt_definitions', ['slug'], unique=False)
    op.create_index(op.f('ix_gov_prompt_definitions_status'), 'gov_prompt_definitions', ['status'], unique=False)
    op.create_index(op.f('ix_gov_prompt_definitions_version'), 'gov_prompt_definitions', ['version'], unique=False)
    op.create_table('obs_intent_cache',
    sa.Column('query_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('predicted_intent', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('raw_results', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('query_hash')
    )
    op.create_index(op.f('ix_obs_intent_cache_expires_at'), 'obs_intent_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_obs_intent_cache_predicted_intent'), 'obs_intent_cache', ['predicted_intent'], unique=False)
    op.create_table('swarm_cognitive_directives',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('directive', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_reflections', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swarm_cognitive_directives_is_active'), 'swarm_cognitive_directives', ['is_active'], unique=False)
    op.create_index(op.f('ix_swarm_cognitive_directives_status'), 'swarm_cognitive_directives', ['status'], unique=False)
    op.create_index(op.f('ix_swarm_cognitive_directives_topic'), 'swarm_cognitive_directives', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_swarm_cognitive_directives_topic'), table_name='swarm_cognitive_directives')
    op.drop_index(op.f('ix_swarm_cognitive_directives_status'), table_name='swarm_cognitive_directives')
    op.drop_index(op.f('ix_swarm_cognitive_directives_is_active'), table_name='swarm_cognitive_directives')
    op.drop_table('swarm_cognitive_directives')
    op.drop_index(op.f('ix_obs_intent_cache_predicted_intent'), table_name='obs_intent_cache')
    op.drop_index(op.f('ix_obs_intent_cache_expires_at'), table_name='obs_intent_cache')
    op.drop_table('obs_intent_cache')
    op.drop_index(op.f('ix_gov_prompt_definitions_version'), table_name='gov_prompt_definitions')
    op.drop_index(op.f('ix_gov_prompt_definitions_status'), table_name='gov_prompt_definitions')
    op.drop_index(op.f('ix_gov_prompt_definitions_slug'), table_name='gov_prompt_definitions')
    op.drop_index(op.f('ix_gov_prompt_definitions_is_current'), table_name='gov_prompt_definitions')
    op.drop_index(op.f('ix_gov_prompt_definitions_created_at'), table_name='gov_prompt_definitions')
    op.drop_table('gov_prompt_definitions')
    # ### end Alembic commands ###
