"""add_details_to_swarm_traces_and_spans

Revision ID: 2ab477643a2a
Revises: 7c82bc6e1ede
Create Date: 2026-04-16 07:03:21.161294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2ab477643a2a'
down_revision: Union[str, None] = '7c82bc6e1ede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('gov_prompt_definitions', 'status',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.Enum('DRAFT', 'ACTIVE', 'DEPRECATED', 'ROLLBACK', name='promptstatus'),
    #            existing_nullable=False)
    op.add_column('obs_swarm_spans', sa.Column('details', sa.JSON(), nullable=True))
    op.add_column('obs_swarm_traces', sa.Column('details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('obs_swarm_traces', 'details')
    op.drop_column('obs_swarm_spans', 'details')
    # op.alter_column('gov_prompt_definitions', 'status',
    #            existing_type=sa.Enum('DRAFT', 'ACTIVE', 'DEPRECATED', 'ROLLBACK', name='promptstatus'),
    #            type_=sa.VARCHAR(),
    #            existing_nullable=False)
    # ### end Alembic commands ###
