"""Add observability models for V3 Swarm

Revision ID: 3a93207357a7
Revises: 5385c217a208
Create Date: 2026-03-07 14:43:04.390119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3a93207357a7'
down_revision: Union[str, None] = '5385c217a208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obs_file_traces',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('batch_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'PENDING_REVIEW', name='tracestatus'), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obs_file_traces_batch_id'), 'obs_file_traces', ['batch_id'], unique=False)
    op.create_index(op.f('ix_obs_file_traces_file_path'), 'obs_file_traces', ['file_path'], unique=False)
    op.create_index(op.f('ix_obs_file_traces_status'), 'obs_file_traces', ['status'], unique=False)
    op.create_table('obs_ingestion_batches',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('completed_files', sa.Integer(), nullable=False),
    sa.Column('failed_files', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obs_agent_spans',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_type', sa.Enum('LLM_CALL', 'TOOL_INVOKE', 'ROUTER', 'AGENT_NODE', name='spantype'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('is_error', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trace_id'], ['obs_file_traces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obs_agent_spans_action_type'), 'obs_agent_spans', ['action_type'], unique=False)
    op.create_index(op.f('ix_obs_agent_spans_agent_name'), 'obs_agent_spans', ['agent_name'], unique=False)
    op.create_index(op.f('ix_obs_agent_spans_trace_id'), 'obs_agent_spans', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_obs_agent_spans_trace_id'), table_name='obs_agent_spans')
    op.drop_index(op.f('ix_obs_agent_spans_agent_name'), table_name='obs_agent_spans')
    op.drop_index(op.f('ix_obs_agent_spans_action_type'), table_name='obs_agent_spans')
    op.drop_table('obs_agent_spans')
    op.drop_table('obs_ingestion_batches')
    op.drop_index(op.f('ix_obs_file_traces_status'), table_name='obs_file_traces')
    op.drop_index(op.f('ix_obs_file_traces_file_path'), table_name='obs_file_traces')
    op.drop_index(op.f('ix_obs_file_traces_batch_id'), table_name='obs_file_traces')
    op.drop_table('obs_file_traces')
    # ### end Alembic commands ###
