"""add_obs_rag_query_traces

Revision ID: 50b82d61e0ea
Revises: 9c21d5a7b2f1
Create Date: 2026-03-13 05:59:35.408704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50b82d61e0ea'
down_revision: Union[str, None] = '9c21d5a7b2f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obs_rag_query_traces',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kb_ids', sa.JSON(), nullable=False),
    sa.Column('retrieval_strategy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_found', sa.Integer(), nullable=False),
    sa.Column('returned_count', sa.Integer(), nullable=False),
    sa.Column('has_results', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('is_error', sa.Boolean(), nullable=False),
    sa.Column('retrieved_doc_ids', sa.JSON(), nullable=False),
    sa.Column('step_traces', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obs_rag_query_traces_created_at'), 'obs_rag_query_traces', ['created_at'], unique=False)
    op.create_index(op.f('ix_obs_rag_query_traces_has_results'), 'obs_rag_query_traces', ['has_results'], unique=False)
    op.create_index(op.f('ix_obs_rag_query_traces_is_error'), 'obs_rag_query_traces', ['is_error'], unique=False)
    op.create_index(op.f('ix_obs_rag_query_traces_query'), 'obs_rag_query_traces', ['query'], unique=False)
    op.create_index(op.f('ix_obs_rag_query_traces_user_id'), 'obs_rag_query_traces', ['user_id'], unique=False)
    op.create_table('obs_hitl_tasks',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extracted_data', sa.JSON(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reviewed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reviewer_comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('final_verdict', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trace_id'], ['obs_file_traces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obs_hitl_tasks_reviewed_by'), 'obs_hitl_tasks', ['reviewed_by'], unique=False)
    op.create_index(op.f('ix_obs_hitl_tasks_trace_id'), 'obs_hitl_tasks', ['trace_id'], unique=False)
    op.drop_index(op.f('ix_pipeline_jobs_doc_id'), table_name='pipeline_jobs')
    op.drop_index(op.f('ix_pipeline_jobs_kb_id'), table_name='pipeline_jobs')
    op.drop_index(op.f('ix_pipeline_jobs_pipeline_name'), table_name='pipeline_jobs')
    op.drop_index(op.f('ix_pipeline_jobs_user_id'), table_name='pipeline_jobs')
    op.drop_table('pipeline_jobs')
    op.drop_index(op.f('ix_pipeline_stage_logs_job_id'), table_name='pipeline_stage_logs')
    op.drop_index(op.f('ix_pipeline_stage_logs_stage_name'), table_name='pipeline_stage_logs')
    op.drop_table('pipeline_stage_logs')
    op.add_column('obs_file_traces', sa.Column('kb_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('obs_file_traces', sa.Column('doc_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('obs_file_traces', sa.Column('result_data', sa.JSON(), nullable=False))
    op.create_index(op.f('ix_obs_file_traces_doc_id'), 'obs_file_traces', ['doc_id'], unique=False)
    op.create_index(op.f('ix_obs_file_traces_kb_id'), 'obs_file_traces', ['kb_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_obs_file_traces_kb_id'), table_name='obs_file_traces')
    op.drop_index(op.f('ix_obs_file_traces_doc_id'), table_name='obs_file_traces')
    op.drop_column('obs_file_traces', 'result_data')
    op.drop_column('obs_file_traces', 'doc_id')
    op.drop_column('obs_file_traces', 'kb_id')
    op.create_table('pipeline_stage_logs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('stage_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_cost', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('input_summary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('output_summary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('artifact_data_json', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['pipeline_jobs.id'], name=op.f('pipeline_stage_logs_job_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pipeline_stage_logs_pkey'))
    )
    op.create_index(op.f('ix_pipeline_stage_logs_stage_name'), 'pipeline_stage_logs', ['stage_name'], unique=False)
    op.create_index(op.f('ix_pipeline_stage_logs_job_id'), 'pipeline_stage_logs', ['job_id'], unique=False)
    op.create_table('pipeline_jobs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pipeline_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pipeline_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('kb_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('doc_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('total_stages', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completed_stages', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_token_cost', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('error_summary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pipeline_jobs_pkey'))
    )
    op.create_index(op.f('ix_pipeline_jobs_user_id'), 'pipeline_jobs', ['user_id'], unique=False)
    op.create_index(op.f('ix_pipeline_jobs_pipeline_name'), 'pipeline_jobs', ['pipeline_name'], unique=False)
    op.create_index(op.f('ix_pipeline_jobs_kb_id'), 'pipeline_jobs', ['kb_id'], unique=False)
    op.create_index(op.f('ix_pipeline_jobs_doc_id'), 'pipeline_jobs', ['doc_id'], unique=False)
    op.drop_index(op.f('ix_obs_hitl_tasks_trace_id'), table_name='obs_hitl_tasks')
    op.drop_index(op.f('ix_obs_hitl_tasks_reviewed_by'), table_name='obs_hitl_tasks')
    op.drop_table('obs_hitl_tasks')
    op.drop_index(op.f('ix_obs_rag_query_traces_user_id'), table_name='obs_rag_query_traces')
    op.drop_index(op.f('ix_obs_rag_query_traces_query'), table_name='obs_rag_query_traces')
    op.drop_index(op.f('ix_obs_rag_query_traces_is_error'), table_name='obs_rag_query_traces')
    op.drop_index(op.f('ix_obs_rag_query_traces_has_results'), table_name='obs_rag_query_traces')
    op.drop_index(op.f('ix_obs_rag_query_traces_created_at'), table_name='obs_rag_query_traces')
    op.drop_table('obs_rag_query_traces')
    # ### end Alembic commands ###
