"""Add KnowledgeBasePermission

Revision ID: 5385c217a208
Revises: f44181f5b576
Create Date: 2026-03-06 03:16:55.845389

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5385c217a208"
down_revision: str | None = "f44181f5b576"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kb_permissions",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("kb_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("role_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("department_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("can_read", sa.Boolean(), nullable=False),
        sa.Column("can_write", sa.Boolean(), nullable=False),
        sa.Column("can_manage", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["kb_id"],
            ["knowledge_bases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_kb_permissions_department_id"), "kb_permissions", ["department_id"], unique=False)
    op.create_index(op.f("ix_kb_permissions_kb_id"), "kb_permissions", ["kb_id"], unique=False)
    op.create_index(op.f("ix_kb_permissions_role_id"), "kb_permissions", ["role_id"], unique=False)
    op.create_index(op.f("ix_kb_permissions_user_id"), "kb_permissions", ["user_id"], unique=False)
    op.create_index(op.f("ix_swarm_todos_assigned_to"), "swarm_todos", ["assigned_to"], unique=False)
    op.create_index(op.f("ix_swarm_todos_status"), "swarm_todos", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_swarm_todos_status"), table_name="swarm_todos")
    op.drop_index(op.f("ix_swarm_todos_assigned_to"), table_name="swarm_todos")
    op.drop_index(op.f("ix_kb_permissions_user_id"), table_name="kb_permissions")
    op.drop_index(op.f("ix_kb_permissions_role_id"), table_name="kb_permissions")
    op.drop_index(op.f("ix_kb_permissions_kb_id"), table_name="kb_permissions")
    op.drop_index(op.f("ix_kb_permissions_department_id"), table_name="kb_permissions")
    op.drop_table("kb_permissions")
    # ### end Alembic commands ###
