"""Add swarm memory and learning models clean

Revision ID: 7b75b52cf7fe
Revises: 1f452e2c036e
Create Date: 2026-04-16 06:34:51.708820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7b75b52cf7fe'
down_revision: Union[str, None] = '1f452e2c036e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swarm_episodes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swarm_episodes_conversation_id'), 'swarm_episodes', ['conversation_id'], unique=False)
    op.create_table('swarm_knowledge',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('knowledge', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('embedding_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swarm_knowledge_category'), 'swarm_knowledge', ['category'], unique=False)
    op.create_index(op.f('ix_swarm_knowledge_embedding_id'), 'swarm_knowledge', ['embedding_id'], unique=False)
    op.create_table('swarm_learning_discoveries',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swarm_learning_discoveries_category'), 'swarm_learning_discoveries', ['category'], unique=False)
    op.create_index(op.f('ix_swarm_learning_discoveries_title'), 'swarm_learning_discoveries', ['title'], unique=False)
    op.create_index(op.f('ix_swarm_learning_discoveries_url'), 'swarm_learning_discoveries', ['url'], unique=False)
    op.create_table('swarm_learning_subscriptions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swarm_learning_subscriptions_is_active'), 'swarm_learning_subscriptions', ['is_active'], unique=False)
    op.create_index(op.f('ix_swarm_learning_subscriptions_topic'), 'swarm_learning_subscriptions', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_swarm_learning_subscriptions_topic'), table_name='swarm_learning_subscriptions')
    op.drop_index(op.f('ix_swarm_learning_subscriptions_is_active'), table_name='swarm_learning_subscriptions')
    op.drop_table('swarm_learning_subscriptions')
    op.drop_index(op.f('ix_swarm_learning_discoveries_url'), table_name='swarm_learning_discoveries')
    op.drop_index(op.f('ix_swarm_learning_discoveries_title'), table_name='swarm_learning_discoveries')
    op.drop_index(op.f('ix_swarm_learning_discoveries_category'), table_name='swarm_learning_discoveries')
    op.drop_table('swarm_learning_discoveries')
    op.drop_index(op.f('ix_swarm_knowledge_embedding_id'), table_name='swarm_knowledge')
    op.drop_index(op.f('ix_swarm_knowledge_category'), table_name='swarm_knowledge')
    op.drop_table('swarm_knowledge')
    op.drop_index(op.f('ix_swarm_episodes_conversation_id'), table_name='swarm_episodes')
    op.drop_table('swarm_episodes')
    # ### end Alembic commands ###
