"""add_status_to_tech_discovery

Revision ID: 7c82bc6e1ede
Revises: 7b75b52cf7fe
Create Date: 2026-04-16 06:47:34.392613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7c82bc6e1ede'
down_revision: Union[str, None] = '7b75b52cf7fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('gov_prompt_definitions', 'status',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.Enum('DRAFT', 'ACTIVE', 'DEPRECATED', 'ROLLBACK', name='promptstatus'),
    #            existing_nullable=False)
    op.add_column('swarm_learning_discoveries', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_swarm_learning_discoveries_status'), 'swarm_learning_discoveries', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_swarm_learning_discoveries_status'), table_name='swarm_learning_discoveries')
    op.drop_column('swarm_learning_discoveries', 'status')
    # op.alter_column('gov_prompt_definitions', 'status',
    #            existing_type=sa.Enum('DRAFT', 'ACTIVE', 'DEPRECATED', 'ROLLBACK', name='promptstatus'),
    #            type_=sa.VARCHAR(),
    #            existing_nullable=False)
    # ### end Alembic commands ###
