"""add_baseline_metrics_table

Revision ID: c050cf2032fd
Revises: da91e273ef7e
Create Date: 2026-03-22 12:20:31.683278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c050cf2032fd'
down_revision: Union[str, None] = 'da91e273ef7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obs_baseline_metrics',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metric_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obs_baseline_metrics_created_at'), 'obs_baseline_metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_obs_baseline_metrics_metric_name'), 'obs_baseline_metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_obs_baseline_metrics_session_id'), 'obs_baseline_metrics', ['session_id'], unique=False)
    op.create_index(op.f('ix_obs_baseline_metrics_user_id'), 'obs_baseline_metrics', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_obs_baseline_metrics_user_id'), table_name='obs_baseline_metrics')
    op.drop_index(op.f('ix_obs_baseline_metrics_session_id'), table_name='obs_baseline_metrics')
    op.drop_index(op.f('ix_obs_baseline_metrics_metric_name'), table_name='obs_baseline_metrics')
    op.drop_index(op.f('ix_obs_baseline_metrics_created_at'), table_name='obs_baseline_metrics')
    op.drop_table('obs_baseline_metrics')
    # ### end Alembic commands ###
