"""add_swarm_observability

Revision ID: cc8659313273
Revises: d86a534d514c
Create Date: 2026-03-26 07:36:02.486047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cc8659313273'
down_revision: Union[str, None] = 'd86a534d514c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql
    op.create_table('obs_swarm_traces',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('triage_reasoning', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'PENDING_REVIEW', 'REJECTED', 'APPROVED', name='tracestatus', create_type=False), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obs_swarm_traces_created_at'), 'obs_swarm_traces', ['created_at'], unique=False)
    op.create_index(op.f('ix_obs_swarm_traces_status'), 'obs_swarm_traces', ['status'], unique=False)
    op.create_index(op.f('ix_obs_swarm_traces_user_id'), 'obs_swarm_traces', ['user_id'], unique=False)
    op.create_table('obs_swarm_spans',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('swarm_trace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'PENDING_REVIEW', 'REJECTED', 'APPROVED', name='tracestatus', create_type=False), nullable=False),
    sa.Column('instruction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('output', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['swarm_trace_id'], ['obs_swarm_traces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obs_swarm_spans_agent_name'), 'obs_swarm_spans', ['agent_name'], unique=False)
    op.create_index(op.f('ix_obs_swarm_spans_created_at'), 'obs_swarm_spans', ['created_at'], unique=False)
    op.create_index(op.f('ix_obs_swarm_spans_swarm_trace_id'), 'obs_swarm_spans', ['swarm_trace_id'], unique=False)
    op.drop_index('idx_obs_rag_h_integrity', table_name='obs_rag_query_traces')
    op.drop_index('idx_obs_rag_p_hash', table_name='obs_rag_query_traces')
    op.create_index(op.f('ix_obs_rag_query_traces_h_integrity'), 'obs_rag_query_traces', ['h_integrity'], unique=False)
    op.create_index(op.f('ix_obs_rag_query_traces_p_hash'), 'obs_rag_query_traces', ['p_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_obs_rag_query_traces_p_hash'), table_name='obs_rag_query_traces')
    op.drop_index(op.f('ix_obs_rag_query_traces_h_integrity'), table_name='obs_rag_query_traces')
    op.create_index('idx_obs_rag_p_hash', 'obs_rag_query_traces', ['p_hash'], unique=False)
    op.create_index('idx_obs_rag_h_integrity', 'obs_rag_query_traces', ['h_integrity'], unique=False)
    op.drop_index(op.f('ix_obs_swarm_spans_swarm_trace_id'), table_name='obs_swarm_spans')
    op.drop_index(op.f('ix_obs_swarm_spans_created_at'), table_name='obs_swarm_spans')
    op.drop_index(op.f('ix_obs_swarm_spans_agent_name'), table_name='obs_swarm_spans')
    op.drop_table('obs_swarm_spans')
    op.drop_index(op.f('ix_obs_swarm_traces_user_id'), table_name='obs_swarm_traces')
    op.drop_index(op.f('ix_obs_swarm_traces_status'), table_name='obs_swarm_traces')
    op.drop_index(op.f('ix_obs_swarm_traces_created_at'), table_name='obs_swarm_traces')
    op.drop_table('obs_swarm_traces')
    # ### end Alembic commands ###
