"""Add Builder Assistant models

Revision ID: cdbdf2219632
Revises: g7c8d9e0f1a2
Create Date: 2026-05-04 01:37:52.162037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdbdf2219632'
down_revision: Union[str, None] = 'g7c8d9e0f1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('builder_agent_configs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tools_config', sa.JSON(), nullable=False),
    sa.Column('kb_bindings', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'DEPRECATED', name='agentstatus'), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_builder_agent_configs_created_by'), 'builder_agent_configs', ['created_by'], unique=False)
    op.create_index(op.f('ix_builder_agent_configs_name'), 'builder_agent_configs', ['name'], unique=False)
    op.create_index(op.f('ix_builder_agent_configs_status'), 'builder_agent_configs', ['status'], unique=False)
    op.create_table('builder_sessions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confirmed_fields', sa.JSON(), nullable=False),
    sa.Column('discovered_context', sa.JSON(), nullable=False),
    sa.Column('research_insights', sa.JSON(), nullable=False),
    sa.Column('coverage_pct', sa.Float(), nullable=False),
    sa.Column('interview_rounds', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Enum('INTERVIEW', 'SANDBOX', 'PUBLISHED', name='builderphase'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['builder_agent_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_builder_sessions_agent_id'), 'builder_sessions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_builder_sessions_phase'), 'builder_sessions', ['phase'], unique=False)
    op.create_index(op.f('ix_builder_sessions_user_id'), 'builder_sessions', ['user_id'], unique=False)
    op.create_table('builder_eval_harnesses',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('builder_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('golden_dataset', sa.JSON(), nullable=False),
    sa.Column('grading_rubric', sa.JSON(), nullable=False),
    sa.Column('cost_budget_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['builder_session_id'], ['builder_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_builder_eval_harnesses_builder_session_id'), 'builder_eval_harnesses', ['builder_session_id'], unique=False)
    op.create_table('builder_sandbox_sessions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('builder_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('eval_harness_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('execution_dag', sa.JSON(), nullable=False),
    sa.Column('process_metrics', sa.JSON(), nullable=False),
    sa.Column('outcome_metrics', sa.JSON(), nullable=False),
    sa.Column('token_cost_usd', sa.Float(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['builder_agent_configs.id'], ),
    sa.ForeignKeyConstraint(['builder_session_id'], ['builder_sessions.id'], ),
    sa.ForeignKeyConstraint(['eval_harness_id'], ['builder_eval_harnesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_builder_sandbox_sessions_agent_id'), 'builder_sandbox_sessions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_builder_sandbox_sessions_builder_session_id'), 'builder_sandbox_sessions', ['builder_session_id'], unique=False)
    op.create_index(op.f('ix_builder_sandbox_sessions_eval_harness_id'), 'builder_sandbox_sessions', ['eval_harness_id'], unique=False)
    op.create_index(op.f('ix_builder_sandbox_sessions_user_id'), 'builder_sandbox_sessions', ['user_id'], unique=False)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_builder_sandbox_sessions_user_id'), table_name='builder_sandbox_sessions')
    op.drop_index(op.f('ix_builder_sandbox_sessions_eval_harness_id'), table_name='builder_sandbox_sessions')
    op.drop_index(op.f('ix_builder_sandbox_sessions_builder_session_id'), table_name='builder_sandbox_sessions')
    op.drop_index(op.f('ix_builder_sandbox_sessions_agent_id'), table_name='builder_sandbox_sessions')
    op.drop_table('builder_sandbox_sessions')
    op.drop_index(op.f('ix_builder_eval_harnesses_builder_session_id'), table_name='builder_eval_harnesses')
    op.drop_table('builder_eval_harnesses')
    op.drop_index(op.f('ix_builder_sessions_user_id'), table_name='builder_sessions')
    op.drop_index(op.f('ix_builder_sessions_phase'), table_name='builder_sessions')
    op.drop_index(op.f('ix_builder_sessions_agent_id'), table_name='builder_sessions')
    op.drop_table('builder_sessions')
    op.drop_index(op.f('ix_builder_agent_configs_status'), table_name='builder_agent_configs')
    op.drop_index(op.f('ix_builder_agent_configs_name'), table_name='builder_agent_configs')
    op.drop_index(op.f('ix_builder_agent_configs_created_by'), table_name='builder_agent_configs')
    op.drop_table('builder_agent_configs')
    # ### end Alembic commands ###
