"""add_ab_execution_metrics_to_swarm_trace

Revision ID: d7fe400c862e
Revises: cc8659313273
Create Date: 2026-04-09 03:22:40.564786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7fe400c862e'
down_revision: Union[str, None] = 'cc8659313273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_obs_intent_cache_expires_at', table_name='obs_intent_cache')
    op.drop_index('ix_obs_intent_cache_predicted_intent', table_name='obs_intent_cache')
    op.drop_table('obs_intent_cache')
    op.drop_index('ix_gov_prompt_definitions_created_at', table_name='gov_prompt_definitions')
    op.drop_index('ix_gov_prompt_definitions_is_current', table_name='gov_prompt_definitions')
    op.drop_index('ix_gov_prompt_definitions_slug', table_name='gov_prompt_definitions')
    op.drop_index('ix_gov_prompt_definitions_status', table_name='gov_prompt_definitions')
    op.drop_index('ix_gov_prompt_definitions_version', table_name='gov_prompt_definitions')
    op.drop_table('gov_prompt_definitions')
    op.add_column('documents', sa.Column('expiry_date', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('last_reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('next_review_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_documents_expiry_date'), 'documents', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_documents_next_review_at'), 'documents', ['next_review_at'], unique=False)
    op.add_column('evaluation_reports', sa.Column('answer_correctness', sa.Float(), nullable=True))
    op.add_column('evaluation_reports', sa.Column('semantic_similarity', sa.Float(), nullable=True))
    op.add_column('obs_swarm_traces', sa.Column('execution_variant', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('obs_swarm_traces', sa.Column('think_time_ms', sa.Float(), nullable=True))
    op.add_column('obs_swarm_traces', sa.Column('tool_time_ms', sa.Float(), nullable=True))
    op.add_column('obs_swarm_traces', sa.Column('num_llm_calls', sa.Integer(), nullable=True))
    op.add_column('obs_swarm_traces', sa.Column('quality_score', sa.Float(), nullable=True))
    op.create_index(op.f('ix_obs_swarm_traces_execution_variant'), 'obs_swarm_traces', ['execution_variant'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_obs_swarm_traces_execution_variant'), table_name='obs_swarm_traces')
    op.drop_column('obs_swarm_traces', 'quality_score')
    op.drop_column('obs_swarm_traces', 'num_llm_calls')
    op.drop_column('obs_swarm_traces', 'tool_time_ms')
    op.drop_column('obs_swarm_traces', 'think_time_ms')
    op.drop_column('obs_swarm_traces', 'execution_variant')
    op.drop_column('evaluation_reports', 'semantic_similarity')
    op.drop_column('evaluation_reports', 'answer_correctness')
    op.drop_index(op.f('ix_documents_next_review_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_expiry_date'), table_name='documents')
    op.drop_column('documents', 'next_review_at')
    op.drop_column('documents', 'last_reviewed_at')
    op.drop_column('documents', 'expiry_date')
    op.create_table('gov_prompt_definitions',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_current', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('recommended_model', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'ACTIVE', 'DEPRECATED', 'ROLLBACK', name='promptstatus'), autoincrement=False, nullable=False),
    sa.Column('change_log', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('meta_info', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='gov_prompt_definitions_pkey')
    )
    op.create_index('ix_gov_prompt_definitions_version', 'gov_prompt_definitions', ['version'], unique=False)
    op.create_index('ix_gov_prompt_definitions_status', 'gov_prompt_definitions', ['status'], unique=False)
    op.create_index('ix_gov_prompt_definitions_slug', 'gov_prompt_definitions', ['slug'], unique=False)
    op.create_index('ix_gov_prompt_definitions_is_current', 'gov_prompt_definitions', ['is_current'], unique=False)
    op.create_index('ix_gov_prompt_definitions_created_at', 'gov_prompt_definitions', ['created_at'], unique=False)
    op.create_table('obs_intent_cache',
    sa.Column('query_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('predicted_intent', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('raw_results', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('query_hash', name='obs_intent_cache_pkey')
    )
    op.create_index('ix_obs_intent_cache_predicted_intent', 'obs_intent_cache', ['predicted_intent'], unique=False)
    op.create_index('ix_obs_intent_cache_expires_at', 'obs_intent_cache', ['expires_at'], unique=False)
    # ### end Alembic commands ###
