"""add_predictive_fields_to_rag_trace

Revision ID: d86a534d514c
Revises: c050cf2032fd
Create Date: 2026-03-26 06:01:01.837295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd86a534d514c'
down_revision: Union[str, None] = 'c050cf2032fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obs_rag_query_traces', sa.Column('prefetch_hit', sa.Boolean(), nullable=False))
    op.add_column('obs_rag_query_traces', sa.Column('intent_predicted', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('obs_rag_query_traces', sa.Column('time_budget_used', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_obs_rag_query_traces_intent_predicted'), 'obs_rag_query_traces', ['intent_predicted'], unique=False)
    op.create_index(op.f('ix_obs_rag_query_traces_prefetch_hit'), 'obs_rag_query_traces', ['prefetch_hit'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_obs_rag_query_traces_prefetch_hit'), table_name='obs_rag_query_traces')
    op.drop_index(op.f('ix_obs_rag_query_traces_intent_predicted'), table_name='obs_rag_query_traces')
    op.drop_column('obs_rag_query_traces', 'time_budget_used')
    op.drop_column('obs_rag_query_traces', 'intent_predicted')
    op.drop_column('obs_rag_query_traces', 'prefetch_hit')
    # ### end Alembic commands ###
