"""Add episodic memory table

Revision ID: da91e273ef7e
Revises: 50b82d61e0ea
Create Date: 2026-03-20 05:13:20.916136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'da91e273ef7e'
down_revision: Union[str, None] = '50b82d61e0ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episodic_memories',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_names', sa.JSON(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_decisions', sa.JSON(), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('user_intent', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('topic_coverage', sa.Float(), nullable=False),
    sa.Column('chroma_doc_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('recall_count', sa.Integer(), nullable=False),
    sa.Column('last_recalled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('conversation_started_at', sa.DateTime(), nullable=True),
    sa.Column('conversation_ended_at', sa.DateTime(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episodic_memories_conversation_id'), 'episodic_memories', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_episodic_memories_created_at'), 'episodic_memories', ['created_at'], unique=False)
    op.create_index(op.f('ix_episodic_memories_user_id'), 'episodic_memories', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episodic_memories_user_id'), table_name='episodic_memories')
    op.drop_index(op.f('ix_episodic_memories_created_at'), table_name='episodic_memories')
    op.drop_index(op.f('ix_episodic_memories_conversation_id'), table_name='episodic_memories')
    op.drop_table('episodic_memories')
    # ### end Alembic commands ###
