"""init_complete_schema

Revision ID: f44181f5b576
Revises:
Create Date: 2026-02-24 14:00:36.642419

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f44181f5b576"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("resource_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("resource_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("details", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ip_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False)
    op.create_table(
        "bad_cases",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("message_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("question", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("bad_answer", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expected_answer", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bad_cases_message_id"), "bad_cases", ["message_id"], unique=False)
    op.create_table(
        "desensitizationpolicy",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("rules_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_desensitizationpolicy_name"), "desensitizationpolicy", ["name"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("file_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("storage_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_documents_content_hash"), "documents", ["content_hash"], unique=False)
    op.create_table(
        "finetuning_items",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("kb_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("instruction", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("input_context", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("output", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_finetuning_items_kb_id"), "finetuning_items", ["kb_id"], unique=False)
    op.create_table(
        "pipeline_jobs",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("pipeline_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("pipeline_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("kb_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("doc_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("total_stages", sa.Integer(), nullable=False),
        sa.Column("completed_stages", sa.Integer(), nullable=False),
        sa.Column("total_token_cost", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("error_summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pipeline_jobs_doc_id"), "pipeline_jobs", ["doc_id"], unique=False)
    op.create_index(op.f("ix_pipeline_jobs_kb_id"), "pipeline_jobs", ["kb_id"], unique=False)
    op.create_index(op.f("ix_pipeline_jobs_pipeline_name"), "pipeline_jobs", ["pipeline_name"], unique=False)
    op.create_index(op.f("ix_pipeline_jobs_user_id"), "pipeline_jobs", ["user_id"], unique=False)
    op.create_table(
        "swarm_reflections",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "SELF_EVAL",
                "ERROR_CORRECTION",
                "KNOWLEDGE_GAP",
                "USER_INTERVENTION",
                "PERIODIC_REVIEW",
                name="reflectiontype",
            ),
            nullable=False,
        ),
        sa.Column("agent_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("action_taken", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_swarm_reflections_agent_name"), "swarm_reflections", ["agent_name"], unique=False)
    op.create_index(op.f("ix_swarm_reflections_type"), "swarm_reflections", ["type"], unique=False)
    op.create_table(
        "tagcategory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tagcategory_name"), "tagcategory", ["name"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("department_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_department_id"), "users", ["department_id"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "conversations",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_conversations_user_id"), "conversations", ["user_id"], unique=False)
    op.create_table(
        "desensitizationreport",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("document_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("total_items_found", sa.Integer(), nullable=False),
        sa.Column("total_items_redacted", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_desensitizationreport_document_id"), "desensitizationreport", ["document_id"], unique=False
    )
    op.create_table(
        "document_chunks",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("document_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("metadata_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("parent_chunk_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_chunk_id"],
            ["document_chunks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_document_chunks_document_id"), "document_chunks", ["document_id"], unique=False)
    op.create_index(op.f("ix_document_chunks_parent_chunk_id"), "document_chunks", ["parent_chunk_id"], unique=False)
    op.create_table(
        "document_permissions",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("document_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("role_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("department_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("can_read", sa.Boolean(), nullable=False),
        sa.Column("can_write", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_permissions_department_id"), "document_permissions", ["department_id"], unique=False
    )
    op.create_index(op.f("ix_document_permissions_document_id"), "document_permissions", ["document_id"], unique=False)
    op.create_index(op.f("ix_document_permissions_role_id"), "document_permissions", ["role_id"], unique=False)
    op.create_index(op.f("ix_document_permissions_user_id"), "document_permissions", ["user_id"], unique=False)
    op.create_table(
        "documentreview",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("document_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reviewer_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("review_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("quality_score", sa.Float(), nullable=False),
        sa.Column("content_length_ok", sa.Boolean(), nullable=False),
        sa.Column("duplicate_ratio", sa.Float(), nullable=False),
        sa.Column("garble_ratio", sa.Float(), nullable=False),
        sa.Column("blank_ratio", sa.Float(), nullable=False),
        sa.Column("overlap_score", sa.Float(), nullable=False),
        sa.Column("reviewer_comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_documentreview_document_id"), "documentreview", ["document_id"], unique=False)
    op.create_index(op.f("ix_documentreview_reviewer_id"), "documentreview", ["reviewer_id"], unique=False)
    op.create_table(
        "knowledge_bases",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("embedding_model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("vector_collection", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("chunking_strategy", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("pipeline_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_knowledge_bases_name"), "knowledge_bases", ["name"], unique=False)
    op.create_index(op.f("ix_knowledge_bases_owner_id"), "knowledge_bases", ["owner_id"], unique=False)
    op.create_table(
        "pipeline_configs",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("pipeline_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("flow_data_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("execution_sequence_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pipeline_configs_name"), "pipeline_configs", ["name"], unique=False)
    op.create_index(op.f("ix_pipeline_configs_owner_id"), "pipeline_configs", ["owner_id"], unique=False)
    op.create_index(op.f("ix_pipeline_configs_pipeline_type"), "pipeline_configs", ["pipeline_type"], unique=False)
    op.create_table(
        "pipeline_stage_logs",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("job_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("stage_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("token_cost", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("input_summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("output_summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("artifact_data_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["pipeline_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pipeline_stage_logs_job_id"), "pipeline_stage_logs", ["job_id"], unique=False)
    op.create_index(op.f("ix_pipeline_stage_logs_stage_name"), "pipeline_stage_logs", ["stage_name"], unique=False)
    op.create_table(
        "tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("color", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["tagcategory.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tag_name"), "tag", ["name"], unique=False)
    op.create_table(
        "documenttaglink",
        sa.Column("document_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.id"],
        ),
        sa.PrimaryKeyConstraint("document_id", "tag_id"),
    )
    op.create_table(
        "evaluation_sets",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("kb_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["kb_id"],
            ["knowledge_bases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evaluation_sets_kb_id"), "evaluation_sets", ["kb_id"], unique=False)
    op.create_table(
        "knowledge_base_documents",
        sa.Column("knowledge_base_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("document_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["knowledge_base_id"],
            ["knowledge_bases.id"],
        ),
        sa.PrimaryKeyConstraint("knowledge_base_id", "document_id"),
    )
    op.create_table(
        "messages",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("conversation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("is_cached", sa.Boolean(), nullable=False),
        sa.Column("trace_data", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False)
    op.create_table(
        "sensitiveitem",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("detector_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("original_text_preview", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("redacted_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start_index", sa.Integer(), nullable=False),
        sa.Column("end_index", sa.Integer(), nullable=False),
        sa.Column("action_taken", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["desensitizationreport.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sensitiveitem_detector_type"), "sensitiveitem", ["detector_type"], unique=False)
    op.create_index(op.f("ix_sensitiveitem_report_id"), "sensitiveitem", ["report_id"], unique=False)
    op.create_table(
        "swarm_todos",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("priority", sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="todopriority"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "IN_PROGRESS", "WAITING_USER", "COMPLETED", "CANCELLED", name="todostatus"),
            nullable=False,
        ),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("assigned_to", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_conversation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("due_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_conversation_id"],
            ["conversations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_swarm_todos_source_conversation_id"), "swarm_todos", ["source_conversation_id"], unique=False
    )
    op.create_index(op.f("ix_swarm_todos_title"), "swarm_todos", ["title"], unique=False)
    op.create_table(
        "sync_tasks",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("knowledge_base_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("config_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("schedule_cron", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(), nullable=True),
        sa.Column("next_run_at", sa.DateTime(), nullable=True),
        sa.Column("last_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["knowledge_base_id"],
            ["knowledge_bases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sync_tasks_knowledge_base_id"), "sync_tasks", ["knowledge_base_id"], unique=False)
    op.create_index(op.f("ix_sync_tasks_source_type"), "sync_tasks", ["source_type"], unique=False)
    op.create_table(
        "evaluation_items",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("set_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("question", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ground_truth", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reference_context", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["set_id"],
            ["evaluation_sets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evaluation_items_set_id"), "evaluation_items", ["set_id"], unique=False)
    op.create_table(
        "evaluation_reports",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("set_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("kb_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("faithfulness", sa.Float(), nullable=False),
        sa.Column("answer_relevance", sa.Float(), nullable=False),
        sa.Column("context_precision", sa.Float(), nullable=False),
        sa.Column("context_recall", sa.Float(), nullable=False),
        sa.Column("total_score", sa.Float(), nullable=False),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("cost", sa.Float(), nullable=False),
        sa.Column("token_usage", sa.Integer(), nullable=False),
        sa.Column("details_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["set_id"],
            ["evaluation_sets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evaluation_reports_kb_id"), "evaluation_reports", ["kb_id"], unique=False)
    op.create_index(op.f("ix_evaluation_reports_model_name"), "evaluation_reports", ["model_name"], unique=False)
    op.create_index(op.f("ix_evaluation_reports_set_id"), "evaluation_reports", ["set_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_evaluation_reports_set_id"), table_name="evaluation_reports")
    op.drop_index(op.f("ix_evaluation_reports_model_name"), table_name="evaluation_reports")
    op.drop_index(op.f("ix_evaluation_reports_kb_id"), table_name="evaluation_reports")
    op.drop_table("evaluation_reports")
    op.drop_index(op.f("ix_evaluation_items_set_id"), table_name="evaluation_items")
    op.drop_table("evaluation_items")
    op.drop_index(op.f("ix_sync_tasks_source_type"), table_name="sync_tasks")
    op.drop_index(op.f("ix_sync_tasks_knowledge_base_id"), table_name="sync_tasks")
    op.drop_table("sync_tasks")
    op.drop_index(op.f("ix_swarm_todos_title"), table_name="swarm_todos")
    op.drop_index(op.f("ix_swarm_todos_source_conversation_id"), table_name="swarm_todos")
    op.drop_table("swarm_todos")
    op.drop_index(op.f("ix_sensitiveitem_report_id"), table_name="sensitiveitem")
    op.drop_index(op.f("ix_sensitiveitem_detector_type"), table_name="sensitiveitem")
    op.drop_table("sensitiveitem")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_table("knowledge_base_documents")
    op.drop_index(op.f("ix_evaluation_sets_kb_id"), table_name="evaluation_sets")
    op.drop_table("evaluation_sets")
    op.drop_table("documenttaglink")
    op.drop_index(op.f("ix_tag_name"), table_name="tag")
    op.drop_table("tag")
    op.drop_index(op.f("ix_pipeline_stage_logs_stage_name"), table_name="pipeline_stage_logs")
    op.drop_index(op.f("ix_pipeline_stage_logs_job_id"), table_name="pipeline_stage_logs")
    op.drop_table("pipeline_stage_logs")
    op.drop_index(op.f("ix_pipeline_configs_pipeline_type"), table_name="pipeline_configs")
    op.drop_index(op.f("ix_pipeline_configs_owner_id"), table_name="pipeline_configs")
    op.drop_index(op.f("ix_pipeline_configs_name"), table_name="pipeline_configs")
    op.drop_table("pipeline_configs")
    op.drop_index(op.f("ix_knowledge_bases_owner_id"), table_name="knowledge_bases")
    op.drop_index(op.f("ix_knowledge_bases_name"), table_name="knowledge_bases")
    op.drop_table("knowledge_bases")
    op.drop_index(op.f("ix_documentreview_reviewer_id"), table_name="documentreview")
    op.drop_index(op.f("ix_documentreview_document_id"), table_name="documentreview")
    op.drop_table("documentreview")
    op.drop_index(op.f("ix_document_permissions_user_id"), table_name="document_permissions")
    op.drop_index(op.f("ix_document_permissions_role_id"), table_name="document_permissions")
    op.drop_index(op.f("ix_document_permissions_document_id"), table_name="document_permissions")
    op.drop_index(op.f("ix_document_permissions_department_id"), table_name="document_permissions")
    op.drop_table("document_permissions")
    op.drop_index(op.f("ix_document_chunks_parent_chunk_id"), table_name="document_chunks")
    op.drop_index(op.f("ix_document_chunks_document_id"), table_name="document_chunks")
    op.drop_table("document_chunks")
    op.drop_index(op.f("ix_desensitizationreport_document_id"), table_name="desensitizationreport")
    op.drop_table("desensitizationreport")
    op.drop_index(op.f("ix_conversations_user_id"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_department_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_tagcategory_name"), table_name="tagcategory")
    op.drop_table("tagcategory")
    op.drop_index(op.f("ix_swarm_reflections_type"), table_name="swarm_reflections")
    op.drop_index(op.f("ix_swarm_reflections_agent_name"), table_name="swarm_reflections")
    op.drop_table("swarm_reflections")
    op.drop_index(op.f("ix_pipeline_jobs_user_id"), table_name="pipeline_jobs")
    op.drop_index(op.f("ix_pipeline_jobs_pipeline_name"), table_name="pipeline_jobs")
    op.drop_index(op.f("ix_pipeline_jobs_kb_id"), table_name="pipeline_jobs")
    op.drop_index(op.f("ix_pipeline_jobs_doc_id"), table_name="pipeline_jobs")
    op.drop_table("pipeline_jobs")
    op.drop_index(op.f("ix_finetuning_items_kb_id"), table_name="finetuning_items")
    op.drop_table("finetuning_items")
    op.drop_index(op.f("ix_documents_content_hash"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_desensitizationpolicy_name"), table_name="desensitizationpolicy")
    op.drop_table("desensitizationpolicy")
    op.drop_index(op.f("ix_bad_cases_message_id"), table_name="bad_cases")
    op.drop_table("bad_cases")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
